### ISSUE TITLE
est_saeOB and est_saeOBns error when samevar is true

### ISSUE THREAD

**Issue by JfrAziz** [yas-q/msaeOB#1]
I just test this package for my project. when I use est_saeOB and est_saeOBns with samevar parameters true it return error noncomfortable array. I think this error from sum of Gn and R or Gn.ns + R.ns, idk what is this.

test code
```R
result <- est_saeOB(
  datamsaeOBns$Y1 ~ datamsaeOBns$X1 + datamsaeOBns$X2, 
  datamsaeOB$v1,
  datamsaeOB$v1,
  samevar = TRUE
)

result <- est_saeOBns(
  datamsaeOBns$Y1 ~ datamsaeOBns$X1 + datamsaeOBns$X2,
  vardir = datamsaeOBns$v1,
  weight = datamsaeOBns$w1,
  cluster = datamsaeOBns$c1,
  samevar = TRUE
)
```

**Comment by yas-q** [comment]
Hello JfrAziz. Thank you very much for your feedback. I have try to fix the error. You may try again this package. If you have try again the package, please tell me if the problem is solved or not. Thank you and good luck for your project.

**Comment by JfrAziz** [comment]
thx for the feedback, will try it later.
